// examples/conduit/frontend/solid/pages/Profile.tsx
import { createSignal, Show, For } from 'solid-js';
import type { ConduitAPI } from '../../shared/api-client.js';
import type { Profile as ProfileType, Article } from '../../shared/types.js';
import type { StoredUser } from '../../shared/auth.js';

const defaultImg = 'https://api.realworld.io/images/smiley-cyrus.jpeg';

interface Props {
  api: ConduitAPI;
  username: string;
  user: StoredUser | null;
}

export function Profile(props: Props) {
  const [profile, setProfile] = createSignal<ProfileType | null>(null);
  const [articles, setArticles] = createSignal<Article[]>([]);
  const [loading, setLoading] = createSignal(true);
  const [error, setError] = createSignal('');

  (async () => {
    try {
      const [profileRes, articlesRes] = await Promise.all([
        props.api.getProfile(props.username),
        props.api.getArticles(),
      ]);
      setProfile(profileRes.profile);
      setArticles(articlesRes.articles.filter(a => a.author.username === props.username));
    } catch (err: any) {
      setError(err.message || 'Failed to load profile');
    } finally {
      setLoading(false);
    }
  })();

  const isOwn = () => props.user?.username === props.username;

  async function toggleFollow() {
    const p = profile();
    if (!p || !props.user) return;
    try {
      const res = p.following
        ? await props.api.unfollow(props.username)
        : await props.api.follow(props.username);
      setProfile(res.profile);
    } catch (err: any) {
      console.error(err);
    }
  }

  async function toggleFavorite(article: Article) {
    if (!props.user) { window.location.hash = '#/login'; return; }
    try {
      const res = article.favorited
        ? await props.api.unfavorite(article.slug)
        : await props.api.favorite(article.slug);
      setArticles(prev => prev.map(a => a.slug === article.slug ? res.article : a));
    } catch (err: any) {
      console.error(err);
    }
  }

  return (
    <Show when={!loading()} fallback={<div class="loading">Loading profile...</div>}>
      <Show when={profile()} fallback={<div class="loading">Profile not found</div>}>
        {(p) => (
          <div>
            <div class="profile-header">
              <img src={p().image || defaultImg} alt={p().username} />
              <h2>{p().username}</h2>
              <Show when={p().bio}>
                <p style="color: #999; margin: 8px 0">{p().bio}</p>
              </Show>
              <Show when={isOwn()} fallback={
                <Show when={props.user}>
                  <button class="btn" style="margin-top: 8px" onClick={toggleFollow}>
                    {p().following ? 'Unfollow' : 'Follow'} {p().username}
                  </button>
                </Show>
              }>
                <a href="#/settings" class="btn" style="margin-top: 8px">Edit Profile Settings</a>
              </Show>
            </div>

            {error() && <div class="error-msg">{error()}</div>}

            <h3 style="margin-bottom: 16px">Articles by {p().username}</h3>
            <Show when={articles().length > 0} fallback={<div class="loading">No articles yet.</div>}>
              <For each={articles()}>
                {(article) => (
                  <div class="card">
                    <div class="article-meta">
                      <img src={article.author.image || defaultImg} alt="" />
                      <div>
                        <a href={`#/profile/${article.author.username}`}>{article.author.username}</a>
                        <div>{new Date(article.createdAt).toLocaleDateString()}</div>
                      </div>
                      <button class="btn" style="margin-left: auto" onClick={() => toggleFavorite(article)}>
                        {article.favorited ? '\u2764' : '\u2661'} {article.favoritesCount}
                      </button>
                    </div>
                    <a href={`#/article/${article.slug}`}>
                      <h2 style="margin: 8px 0 4px; color: #333">{article.title}</h2>
                      <p style="color: #999; font-size: 0.9rem">{article.description}</p>
                    </a>
                    <div style="margin-top: 8px">
                      <For each={article.tagList}>
                        {(tag) => <span class="tag">{tag}</span>}
                      </For>
                    </div>
                  </div>
                )}
              </For>
            </Show>
          </div>
        )}
      </Show>
    </Show>
  );
}

// examples/conduit/frontend/svelte/pages/Profile.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { ConduitAPI } from '../../shared/api-client.js';
  import type { Profile, Article } from '../../shared/types.js';
  import type { StoredUser } from '../../shared/auth.js';

  export let api: ConduitAPI;
  export let username: string;
  export let user: StoredUser | null;

  const defaultImg = 'https://api.realworld.io/images/smiley-cyrus.jpeg';

  let profile: Profile | null = null;
  let articles: Article[] = [];
  let loading = true;
  let error = '';

  $: isOwn = user?.username === username;

  onMount(loadProfile);

  async function loadProfile() {
    loading = true;
    try {
      const [profileRes, articlesRes] = await Promise.all([
        api.getProfile(username),
        api.getArticles(),
      ]);
      profile = profileRes.profile;
      articles = articlesRes.articles.filter(a => a.author.username === username);
    } catch (err: any) {
      error = err.message || 'Failed to load profile';
    } finally {
      loading = false;
    }
  }

  async function toggleFollow() {
    if (!profile || !user) return;
    try {
      const res = profile.following
        ? await api.unfollow(username)
        : await api.follow(username);
      profile = res.profile;
    } catch (err: any) {
      console.error(err);
    }
  }

  async function toggleFavorite(article: Article) {
    if (!user) { window.location.hash = '#/login'; return; }
    try {
      const res = article.favorited
        ? await api.unfavorite(article.slug)
        : await api.favorite(article.slug);
      articles = articles.map(a => a.slug === article.slug ? res.article : a);
    } catch (err: any) {
      console.error(err);
    }
  }
</script>

{#if loading}
  <div class="loading">Loading profile...</div>
{:else if !profile}
  <div class="loading">Profile not found</div>
{:else}
  <div class="profile-header">
    <img src={profile.image || defaultImg} alt={profile.username} />
    <h2>{profile.username}</h2>
    {#if profile.bio}
      <p style="color: #999; margin: 8px 0">{profile.bio}</p>
    {/if}
    {#if isOwn}
      <a href="#/settings" class="btn" style="margin-top: 8px">Edit Profile Settings</a>
    {:else if user}
      <button class="btn" style="margin-top: 8px" on:click={toggleFollow}>
        {profile.following ? 'Unfollow' : 'Follow'} {profile.username}
      </button>
    {/if}
  </div>

  {#if error}
    <div class="error-msg">{error}</div>
  {/if}

  <h3 style="margin-bottom: 16px">Articles by {profile.username}</h3>
  {#if articles.length === 0}
    <div class="loading">No articles yet.</div>
  {:else}
    {#each articles as article (article.slug)}
      <div class="card">
        <div class="article-meta">
          <img src={article.author.image || defaultImg} alt="" />
          <div>
            <a href="#/profile/{article.author.username}">{article.author.username}</a>
            <div>{new Date(article.createdAt).toLocaleDateString()}</div>
          </div>
          <button class="btn" style="margin-left: auto" on:click={() => toggleFavorite(article)}>
            {article.favorited ? '\u2764' : '\u2661'} {article.favoritesCount}
          </button>
        </div>
        <a href="#/article/{article.slug}">
          <h2 style="margin: 8px 0 4px; color: #333">{article.title}</h2>
          <p style="color: #999; font-size: 0.9rem">{article.description}</p>
        </a>
        <div style="margin-top: 8px">
          {#each article.tagList as tag}
            <span class="tag">{tag}</span>
          {/each}
        </div>
      </div>
    {/each}
  {/if}
{/if}
